include mime.types;

types {
  application/javascript mjs;
}

server {
    listen 80;
    server_name localhost;

    root   /opt/amaral-sofware;
    index  index.html index.htm;

    location / {
        alias /opt/amaral-sofware/portal/;
        try_files $uri /index.html;
    }

    location ~ ^/(sample|videoGameCatalog|shelveProducts)/(.*)$ {
        try_files $uri $uri/ /$1/remoteEntry.mjs;

        if ($uri = /$1/remoteEntry.mjs) {
            add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            expires -1;
        }
    }

    location ~ ^/assets/(sample|videoGameCatalog|shelveProducts)/(.*)$ {
        alias /opt/amaral-sofware/$1/assets/$2;
    }

    location /shelve/api {
        proxy_pass http://backend:8080/shelve/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Block common attack vectors
    location ~* \.(aspx|php|jsp|cgi)$ {
        deny all;
    }

    # Block access to sensitive files
    location ~* \.(sql|log|conf|ini|bak|backup|old|tmp)$ {
        deny all;
    }

    # Deny all attempts to access hidden files such as .htaccess or .htpasswd
    location ~ /\. {
        deny all;
    }

    # Deny access to any files with a .php extension in the uploads directory
    # See: https://developer.wordpress.org/advanced-administration/server/web-server/nginx/#global-restrictions-file
    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }
}
