include mime.types;

types {
  application/javascript mjs;
}

server {
    listen 80;
    server_name localhost;

    root   /opt/amaral-sofware;
    index  index.html index.htm;

    location / {
        root /opt/amaral-sofware/portal/browser;
        index index.html;

        location ~* \.(js|mjs|json|css|woff2?|png|svg|ico)$ {
            try_files $uri =404;
        }

        try_files $uri $uri/ /index.html;
    }

    location = /shelveProducts/remoteEntry.json {
        alias /opt/amaral-sofware/shelveProducts/browser/remoteEntry.json;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        expires -1;
    }

    location /assets/shelveProducts/ {
        alias /opt/amaral-sofware/shelveProducts/browser/assets/;
        try_files $uri $uri/ =404;
    }

    location /shelveProducts/ {
        alias /opt/amaral-sofware/shelveProducts/browser/;
        try_files $uri $uri/ =404;
    }

    location = /gameVault/remoteEntry.json {
        alias /opt/amaral-sofware/gameVault/browser/remoteEntry.json;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
        expires -1;
    }

    location /assets/gameVault/ {
        alias /opt/amaral-sofware/gameVault/browser/assets/;
        try_files $uri $uri/ =404;
    }

    location /gameVault/ {
        alias /opt/amaral-sofware/gameVault/browser/;
        try_files $uri $uri/ =404;
    }

    location /shelve/api {
        proxy_pass http://backend:8088/shelve/api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Block common attack vectors
    location ~* \.(aspx|php|jsp|cgi)$ {
        deny all;
    }

    # Block access to sensitive files
    location ~* \.(sql|log|conf|ini|bak|backup|old|tmp)$ {
        deny all;
    }

    # Deny all attempts to access hidden files such as .htaccess or .htpasswd
    location ~ /\. {
        deny all;
    }

    # Deny access to any files with a .php extension in the uploads directory
    # See: https://developer.wordpress.org/advanced-administration/server/web-server/nginx/#global-restrictions-file
    location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
    }
}
