quarkus.http.port=8088

quarkus.log.level=INFO

# DataBase configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.url=${DATABASE_URL}

# Hibernate
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db

# Nfty
quarkus.rest-client.ntfy.url=${NTFY_URL}
ntfy.topic=${NTFY_TOPIC}
ntfy.user=${NTFY_USER}
ntfy.password=${NTFY_PASSWORD}

#Keycloak
quarkus.rest-client.keycloak.url=http://localhost:8080
quarkus.oidc.application-type=web-app
quarkus.oidc.auth-server-url=http://localhost:8080/realms/centralhub
quarkus.oidc.client-id=confidential-client
quarkus.oidc.credentials.secret=yv6Y6IibLfVUgJkAwoGkVsJ9IUiqYZc4
quarkus.oidc.authentication.user-info-required=true

quarkus.oidc.authentication.cookie-path=/
quarkus.http.proxy.proxy-address-forwarding=true

quarkus.oidc.authentication.redirect-path=/callback
quarkus.oidc.authentication.restore-path-after-redirect=true

quarkus.http.auth.permission.authenticated.paths=/logout
quarkus.http.auth.permission.authenticated.policy=authenticated
