FROM node:22-alpine AS builder

WORKDIR /app

COPY --chown=185:0 . .

RUN npm install \
 && npm run build

FROM nginxinc/nginx-unprivileged:1.29.1-alpine as runner

USER root

RUN apk update \
 && apk add --no-cache curl unzip bash

RUN mkdir -p /opt/amaral-sofware/bin/ \
 && mkdir -p /opt/amaral-sofware/scripts/

USER 185

COPY --chmod=770 /buildfiles/conf/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder --chown=185 --chmod=770 /app/buildfiles/scripts/ /opt/amaral-sofware/scripts/
COPY --from=builder --chown=185 --chmod=770 /app/dist/packages /opt/amaral-sofware

CMD ["/opt/amaral-sofware/scripts/run.sh"]

EXPOSE 8080
