name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, unraid, linux]
    defaults:
      run:
        working-directory: src/frontend/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Run lint script
        run: npm run lint
      

#  unit-test:
#    name: Unit Tests
#    runs-on: [self-hosted, unraid, linux]
#    needs: lint
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run test -- --watch=false --browsers=ChromeHeadless

#  e2e:
#    name: E2E Tests
#    runs-on: [self-hosted, unraid, linux]
#    needs: lint
#    if: github.event_name == 'pull_request'
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run e2e -- --watch=false

#  build-check:
#    name: Dry-Run Build
#    runs-on: [self-hosted, unraid, linux]
#    needs: [unit-test, e2e]
#    if: always() && needs.unit-test.result == 'success'
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run build