name: CD — Build & Push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag (e.g. 1.0.0)'
        required: true
        type: string

env:
  NX_NO_CLOUD: 'true'

jobs:
  tag:
    name: Create Git Tag, Build & Push Frontend
    runs-on: [self-hosted, unraid, linux]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check actor is repo owner
        if: github.actor != 'joao-l-amaral'
        run: echo "❌ Unauthorized" && exit 1

      - name: Create git tag
        run: |
          git config user.name "joao-l-amaral"
          git config user.email "joaoamaral1989@hotmail.com"
          git tag v${{ inputs.tag }}
          git push origin v${{ inputs.tag }}

      - name: Build & Push Docker image
        working-directory: build
        run: |
          chmod +x build/createImage.sh
          ./createImage.sh -t ${{ inputs.tag }} -r 100.92.117.108 -p      

  #build-backend:
  #  name: Build & Push Backend
  #  runs-on: [self-hosted, unraid, linux]
  #  needs: tag
  #  defaults:
  #    run:
  #      working-directory: src/backend
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        ref: v${{ inputs.tag }}    # ← checkout the tag we just created
#
  #    - uses: actions/setup-java@v4
  #      with:
  #        java-version: 21
  #        distribution: temurin
  #        cache: maven
#
  #    - name: Build backend
  #      run: ./mvnw package -DskipTests
#
  #    - name: Build & Push Docker image
  #      run: |
  #        chmod +x build/createimage.sh
  #        ./build/createimage.sh \
  #          --tag ${{ inputs.tag }} \
  #          --registry localhost:5000